bugfix: fixup of catalog definition for int4(int1), and related.
CREATE TABLE test_for_int21(
  id   int,
  a    int2,
  b    int1
);
INSERT INTO test_for_int21 (
  SELECT x,1,x%256-128
   FROM generate_series(1,2000) x);

% SET enable_seqscan = off;
% SELECT CASE WHEN b BETWEEN -64 AND 63 THEN b+b ELSE 0 END from test_for_int21 where id=1;

The above query raised error.

ERROR:  GPU kernel: integer out of range
DETAIL:  GPU kernel location: cuda_primitive.cu:86 [pgfn_int1pl]

Because int4(int1) [type cast] was not defined at the catalog
correctly, the above CASE WHEN ... END clause was split into
two portions, thus GPU code tried to calculate the (b+b) preliminary,
even though the CASE WHEN clause intends to avoid potential overflow.

This fix also prohibit to run a part of some expression type in
GPU devices.